package:
  name: afem
  version: "1.1.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python

  run:
    - python
    - wxpython
    - numpy
    - scipy
    - pyocct ==7.4.0.0
    
test:
  source_files:
  - test

about:
  home: https://github.com/LaughlinResearch/AFEM
  license: LGPL2.1
  license_family: LGPL
  summary: Airframe Finite Element Modeler
  description: A "fit-for-purpose" engineering development toolkit designed to
               support the use of high-order structural analysis during the
               early phases of aircraft conceptual design.
