name: Workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published, prereleased]

jobs:
  build_linux:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:

      - name: "Install OpenGL"
        run: |
          sudo apt-get update
          sudo apt-get -q -y install libglu1-mesa-dev libgl1-mesa-dev libxi-dev libglfw3-dev libgles2-mesa-dev

      - name: "Clone AFEM"
        uses: actions/checkout@v2

      - name: "Install conda build"
        shell: pwsh
        run: conda install -c conda-forge conda-build

      - name: "Check conda"
        shell: pwsh
        run: |
          conda info -a
          conda list

      - name: "Run conda build"
        shell: pwsh
        run: |
          mkdir conda
          conda build  ci/conda -c conda-forge -c trelau --python ${{ matrix.python-version }} --output-folder conda

      - name: "Upload conda package"
        uses: actions/upload-artifact@v2
        with:
          name: afem-py${{ matrix.python-version }}_${{ matrix.os }}
          path: conda

  build_win:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:

      - name: "Clone AFEM"
        uses: actions/checkout@v2

      - name: "Add conda to PATH"
        shell: bash -l {0}
        run: echo "::add-path::$CONDA/Scripts"

      - name: "Install conda build"
        shell: bash -l {0}
        run: conda install -c conda-forge conda-build

      - name: "Check conda"
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: "Run conda build"
        shell: bash -l {0}
        run: |
          mkdir conda
          source activate
          conda build  ci/conda -c conda-forge -c trelau --python ${{ matrix.python-version }} --output-folder conda

      - name: "Upload conda package"
        uses: actions/upload-artifact@v2
        with:
          name: afem-py${{ matrix.python-version }}_${{ matrix.os }}
          path: conda
